### ISSUE TITLE
Add smooth-scroll

### ISSUE THREAD

**Issue by binyamin** [akivajgordon/tikkun.io#62]
Useful when scrolling via keyboard (directional keys, page up/down, etc.). Without getting too deep into browser support, this is as simple as a couple lines of css:
```css
html {
    scroll-behavior: smooth;
}
```
